
package pl.bb.broker.brokerinvoices.ws.debtcollection;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DebtCollectionService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://localhost:65354/BattleService.svc?wsdl")
public class DebtCollectionService
    extends Service
{

    private final static URL DEBTCOLLECTIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException DEBTCOLLECTIONSERVICE_EXCEPTION;
    private final static QName DEBTCOLLECTIONSERVICE_QNAME = new QName("http://tempuri.org/", "DebtCollectionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:65354/BattleService.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DEBTCOLLECTIONSERVICE_WSDL_LOCATION = url;
        DEBTCOLLECTIONSERVICE_EXCEPTION = e;
    }

    public DebtCollectionService() {
        super(__getWsdlLocation(), DEBTCOLLECTIONSERVICE_QNAME);
    }

    public DebtCollectionService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DEBTCOLLECTIONSERVICE_QNAME, features);
    }

    public DebtCollectionService(URL wsdlLocation) {
        super(wsdlLocation, DEBTCOLLECTIONSERVICE_QNAME);
    }

    public DebtCollectionService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DEBTCOLLECTIONSERVICE_QNAME, features);
    }

    public DebtCollectionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DebtCollectionService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IDebtCollectionService
     */
    @WebEndpoint(name = "WSHttpBinding_IDebtCollectionService")
    public IDebtCollectionService getWSHttpBindingIDebtCollectionService() {
        return super.getPort(new QName("http://tempuri.org/", "WSHttpBinding_IDebtCollectionService"), IDebtCollectionService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IDebtCollectionService
     */
    @WebEndpoint(name = "WSHttpBinding_IDebtCollectionService")
    public IDebtCollectionService getWSHttpBindingIDebtCollectionService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "WSHttpBinding_IDebtCollectionService"), IDebtCollectionService.class, features);
    }

    /**
     * 
     * @return
     *     returns IDebtCollectionService
     */
    @WebEndpoint(name = "BasicHttpBinding_IDebtCollectionService")
    public IDebtCollectionService getBasicHttpBindingIDebtCollectionService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IDebtCollectionService"), IDebtCollectionService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IDebtCollectionService
     */
    @WebEndpoint(name = "BasicHttpBinding_IDebtCollectionService")
    public IDebtCollectionService getBasicHttpBindingIDebtCollectionService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IDebtCollectionService"), IDebtCollectionService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DEBTCOLLECTIONSERVICE_EXCEPTION!= null) {
            throw DEBTCOLLECTIONSERVICE_EXCEPTION;
        }
        return DEBTCOLLECTIONSERVICE_WSDL_LOCATION;
    }

}
