
package pl.bb.broker.brokerinvoices.ws.debtcollection;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IDebtCollectionService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IDebtCollectionService {


    /**
     * 
     * @param invoice
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/IDebtCollectionService/transferInvoice")
    @WebResult(name = "transferInvoiceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "transferInvoice", targetNamespace = "http://tempuri.org/", className = "pl.bb.broker.brokerinvoices.ws.debtcollection.TransferInvoice")
    @ResponseWrapper(localName = "transferInvoiceResponse", targetNamespace = "http://tempuri.org/", className = "pl.bb.broker.brokerinvoices.ws.debtcollection.TransferInvoiceResponse")
    public String transferInvoice(
        @WebParam(name = "invoice", targetNamespace = "http://tempuri.org/")
        Invoice invoice);

}
